In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np

arr = np.arange(0, 6)
print(arr)
print("Data type:", arr.dtype)

[0 1 2 3 4 5]
Data type: int64


In [2]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print("Is float64:", is_float64)

Is float64: True


In [3]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print("Data type:", arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [4]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
 
 
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("Data type:", arr_float32.dtype)

[1. 2. 3. 4. 5.]
Data type: float32


In [5]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
 
 
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print("Data type:", arr_float32.dtype)


[1.5 2.6 3.7]
Data type: float32


In [6]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
 
 
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1.5, 2.6, 3.7])
print(array_attributes(arr))

((3,), 3, dtype('float64'))


In [7]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
 
 
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1.5, 2.6, 3.7], [4.5, 5.6, 6.7]])
print(array_dimension(arr))

2


In [8]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
 
 
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1.5, 2.6, 3.7])
print(item_size_info(arr))

(8, 24)


In [9]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
 
 
def array_strides(arr):
    return arr.strides

arr = np.array([[1.5, 2.6, 3.7], [4.5, 5.6, 6.7]])
print(array_strides(arr))

(24, 8)


In [10]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
 
 
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1.5, 2.6, 3.7], [4.5, 5.6, 6.7]])
print(shape_stride_relationship(arr))

((2, 3), (24, 8))


In [11]:
#11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.
 
 
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [12]:
#12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.
 
 
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.
 
 
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [14]:
#14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).
 
 
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.
 
 
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#16. Write a function that takes a  list and converts it into a NumPy array.
 
 
def list_to_numpy_array(lst):
    return np.array(lst)

print(list_to_numpy_array([1, 2, 3, 4, 5]))

[1 2 3 4 5]


In [18]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data.

import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view to create a new array object with the same data
view_array = original_array.view()

# Display the original and the view arrays
print("Original Array:", original_array)
print("View Array:", view_array)

# Modify the view array
view_array[0] = 10

# Display the arrays after modification to show that the data is shared
print("Original Array after modification:", original_array)
print("View Array after modification:", view_array)

Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]
Original Array after modification: [10  2  3  4  5]
View Array after modification: [10  2  3  4  5]


In [19]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
 
 
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))
print(concatenate_arrays(arr1, arr2, axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [20]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.
 
 
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])
print(np.concatenate((arr1, arr2.T), axis=1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [21]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
 
 
def stack_vertically(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
print(stack_vertically([arr1, arr2, arr3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#21. Write a  function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
 
 
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [24]:
#22. Write a  function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
 
 
def generate_equally_spaced_array(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_equally_spaced_array(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
#23. Write a  function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
 
 
def generate_log_space_array(start, stop, num):
    return np.logspace(np.log10(start), np.log10(stop), num)

print(generate_log_space_array(1, 1000, 5))

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [26]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
 
 
import pandas as pd

def create_random_dataframe(rows, cols, min_val, max_val):
    data = np.random.randint(min_val, max_val + 1, size=(rows, cols))
    return pd.DataFrame(data, columns=[f'col{i+1}' for i in range(cols)])

print(create_random_dataframe(5, 3, 1, 100))

   col1  col2  col3
0    86    84    17
1    79    71    49
2    25    45    48
3    35    96    55
4    60    64    31


In [27]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
 
 
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5]
})
print(replace_negatives_with_zero(df, 'A'))

   A  B
0  1 -1
1  0  2
2  3 -3
3  0  4
4  5 -5


In [28]:
#26. Access the 3rd element from the given NumPy array.
 
 
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [29]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
 
 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])


6


In [30]:
#28: Using boolean indexing, extract elements greater than 5 from the given NumPy array
 
 
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)

[ 8 10  7]


In [31]:
#29: Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
 
 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[2:6]  # Slicing is exclusive of the end index, so we use 6 to include element at index 5
print(result)

[3 4 5 6]


In [32]:
#30: Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array
 
 
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
result = arr_2d[0:2, 1:3]
print(result)

[[2 3]
 [5 6]]


In [33]:
#31: Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array
 
 
import numpy as np

def extract_elements(arr, indices):
    return arr[indices]

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
indices = np.array([[0, 1], 
                    [1, 2]])
result = extract_elements(arr, indices)
print(result)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [34]:
#32: Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing
 
 
import numpy as np

def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5
result = filter_elements(arr, threshold)
print(result)

[6 7 8 9]


In [35]:
#33: Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension
 
 
import numpy as np

def extract_elements_3d(arr, indices_x, indices_y, indices_z):
    return arr[indices_x, indices_y, indices_z]

arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
indices_x = np.array([0, 1])
indices_y = np.array([0, 1])
indices_z = np.array([2, 1])
result = extract_elements_3d(arr, indices_x, indices_y, indices_z)
print(result)

[ 3 11]


In [36]:
#34: Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing
 
 
import numpy as np

def filter_elements_two_conditions(arr, condition1, condition2):
    return arr[condition1 & condition2]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr > 3
condition2 = arr < 8
result = filter_elements_two_conditions(arr, condition1, condition2)
print(result)

[4 5 6 7]


In [37]:
# 35: Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays
 
 
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = extract_elements_2d(arr, row_indices, col_indices)
print(result)

[2 6 7]


In [38]:
# 36: Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting
 
 
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
result = arr + 5
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
# 37: Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting
 
 
import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]])
result = arr2 * arr1.T  # Transpose arr1 to shape (3, 1) for broadcasting
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [40]:
# 38: Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting
 
 
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9], 
                 [10, 11, 12]])
result = arr2 + arr1.T  # Transpose arr1 to shape (4, 1) for broadcasting
print(result)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [41]:
#39: Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting
 
 
import numpy as np

arr1 = np.array([[1], 
                 [2], 
                 [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [43]:
# 40: Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility
#Since the shapes (2, 3) and (2, 2) are incompatible for broadcasting, we can adjust the dimensions of one of the arrays to make them compatible. We can use a combination of broadcasting and manual adjustment to achieve the multiplication:


import numpy as np

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr2 = np.array([[7, 8], 
                 [9, 10]])

# To make the shapes compatible, we need to expand the dimensions of arr2
# For example, we can add a new axis to arr2 to make its shape (2, 2, 1)
arr2_expanded = arr2[:, :, np.newaxis]

# Now we can broadcast arr1 to the shape of arr2_expanded and perform the multiplication
result = arr1[:, np.newaxis, :] * arr2_expanded
print(result)


[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


In [44]:
 # 41: Calculate column-wise mean for the given array
 
 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_wise_mean = np.mean(arr, axis=0)
print("Column-wise mean:", column_wise_mean)

Column-wise mean: [2.5 3.5 4.5]


In [45]:
 # 42: Find maximum value in each row of the given array
 
 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
row_wise_max = np.max(arr, axis=1)
print("Maximum value in each row:", row_wise_max)
 # 43: For the given array, find indices of maximum value in each column
 
 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
indices_max_value = np.argmax(arr, axis=0)
print("Indices of maximum value in each column:", indices_max_value)

Maximum value in each row: [3 6]
Indices of maximum value in each column: [1 1 1]


In [46]:
 # 44: For the given array, apply custom function to calculate moving sum along rows
 
 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr):
    result = np.cumsum(arr, axis=1)
    return result

moving_sum_result = moving_sum(arr)
print("Moving sum along rows:", moving_sum_result)

Moving sum along rows: [[ 1  3  6]
 [ 4  9 15]]


In [47]:
 # 45: In the given array, check if all elements in each column are even
 
 
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])
are_all_even = np.all(arr % 2 == 0, axis=0)
print("Are all elements in each column even:", are_all_even)

Are all elements in each column even: [False False False]


In [48]:
 # 46: Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns
 
 
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = original_array.reshape(2, 3)  # Example: 2 rows and 3 columns
print("Reshaped matrix:\n", reshaped_matrix)

Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [49]:
# 47: Create a function that takes a matrix as input and returns the flattened array
 
 
import numpy as np

def flatten_matrix(matrix):
    flattened = matrix.flatten()
    return flattened

matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(matrix)
print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [50]:
 # 48: Write a function that concatenates two given arrays along a specified axis
 
 
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0:\n", concatenated_array)

Concatenated array along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
 # 49: Create a function that splits an array into multiple sub-arrays along a specified axis
 
 
import numpy as np

def split_array(array, indices_or_sections, axis=0):
    return np.split(array, indices_or_sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = split_array(original_array, 3, axis=0)
print("Split arrays:\n", split_arrays)

Split arrays:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [52]:
 # 50: Write a function that inserts and then deletes elements from a given array at specified indices
 
 
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    modified_array = np.delete(modified_array, indices_to_delete)
    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", modified_array)

Modified array: [ 1 10  4 11  5]


In [53]:
 # 51: Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2
 
 
import numpy as np

arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 11)
element_wise_addition = np.add(arr1, arr2)
print("Element-wise addition:", element_wise_addition)

Element-wise addition: [ 7  4  6  5  7 16 17 18 10 15]


In [54]:
 # 52: Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise
 
 
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
element_wise_subtraction = np.subtract(arr1, arr2)
print("Element-wise subtraction:", element_wise_subtraction)

Element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [55]:
# 53: Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2
 
 
import numpy as np

arr1 = np.random.randint(1, 11, size=5)
arr2 = np.arange(1, 6)
element_wise_multiplication = np.multiply(arr1, arr2)
print("Element-wise multiplication:", element_wise_multiplication)

Element-wise multiplication: [ 7  6  6 28 35]


In [56]:
 # 54: Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2
 
 
import numpy as np

arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)
element_wise_division = np.divide(arr1, arr2)
print("Element-wise division:", element_wise_division)

Element-wise division: [2. 2. 2. 2. 2.]


In [57]:
 # 58: Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
 
 
import numpy as np

def replace_substring(array, old_substring, new_substring):
    return np.char.replace(array, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'
replaced_array = replace_substring(arr, old_substring, new_substring)
print("Array after replacing substring:\n", replaced_array)

Array after replacing substring:
 ['fruit' 'banana' 'grape' 'pinefruit']


In [58]:
 # 59: Write a function that concatenates strings in a NumPy array element-wise
 
 
import numpy as np

def concatenate_strings(array1, array2):
    return np.char.add(array1, array2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_array = concatenate_strings(arr1, arr2)
print("Element-wise concatenated array:\n", concatenated_array)

Element-wise concatenated array:
 ['HelloOpen' 'WorldAI']


In [59]:
 # 60: Write a function that finds the length of the longest string in a NumPy array
 
 
import numpy as np

def length_of_longest_string(array):
    return np.max(np.char.str_len(array))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_string_length = length_of_longest_string(arr)
print("Length of the longest string:", longest_string_length)

Length of the longest string: 9


In [60]:
 # 61: Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions
 
 
import numpy as np

dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Dataset statistics:")
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Dataset statistics:
Mean: 490.7
Median: 465.5
Variance: 81161.38999999998
Standard Deviation: 284.88838165148115


In [61]:
 # 62: Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset
 
 
import numpy as np

random_numbers = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

25th Percentile: 29.0
75th Percentile: 73.0


In [62]:
 # 63: Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function
 
 
import numpy as np

array1 = np.random.randint(1, 101, size=50)
array2 = np.random.randint(1, 101, size=50)
correlation_coefficient = np.corrcoef(array1, array2)

print("Correlation coefficient matrix:\n", correlation_coefficient)

Correlation coefficient matrix:
 [[ 1.         -0.05686489]
 [-0.05686489  1.        ]]


In [63]:
 # 64: Create two matrices and perform matrix multiplication using NumPy's dot function
 
 
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)

print("Matrix product:\n", matrix_product)

Matrix product:
 [[19 22]
 [43 50]]


In [64]:
 # 65: Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles
 
 
import numpy as np

array = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(array, 10)
median = np.median(array)
percentile_90 = np.percentile(array, 90)
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("10th Percentile:", percentile_10)
print("Median:", median)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)

10th Percentile: 111.4
Median: 420.5
90th Percentile: 842.6
First Quartile (25th Percentile): 227.25
Third Quartile (75th Percentile): 637.75


In [65]:
 # 66: Create a NumPy array of integers and find the index of a specific element
 
 
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
element_to_find = 4
index = np.where(array == element_to_find)[0]

print("Index of the element:", index)

Index of the element: [3]


In [66]:
 # 67: Generate a random NumPy array and sort it in ascending order
 
 
import numpy as np

random_array = np.random.randint(1, 101, size=10)
sorted_array = np.sort(random_array)

print("Sorted array:", sorted_array)

Sorted array: [ 2 22 33 36 38 64 69 78 80 91]


In [67]:
 # 68: Filter elements >20 in the given NumPy array
 
 
import numpy as np

arr = np.array([112, 25, 60, 42, 8, 30])
filtered_array = arr[arr > 20]

print("Filtered array with elements >20:", filtered_array)

Filtered array with elements >20: [112  25  60  42  30]


In [68]:
 # 72: Perform byte swapping in place using byteswap()
 
 
import numpy as np

arr = np.array([1, 256, 65536], dtype=np.int32)
arr.byteswap(inplace=True)
print("Array after byte swapping in place:", arr)

Array after byte swapping in place: [16777216    65536      256]


In [69]:
 # 73: Swap its byte order without modifying the original array using newbyteorder()
 
 
import numpy as np

arr = np.array([1, 256, 65536], dtype=np.int32)
swapped_arr = arr.byteswap().newbyteorder()
print("Original array:", arr)
print("Array after swapping byte order:", swapped_arr)

Original array: [    1   256 65536]
Array after swapping byte order: [    1   256 65536]


In [70]:
 # 74: Swap its byte order conditionally based on system endianness using newbyteorder()
 
 
import numpy as np

arr = np.array([1, 256, 65536], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native byte order
    swapped_arr = arr.byteswap().newbyteorder()
else:
    swapped_arr = arr

print("Original array:", arr)
print("Conditionally byte-swapped array:", swapped_arr)

Original array: [    1   256 65536]
Conditionally byte-swapped array: [    1   256 65536]


In [71]:
 # 75: Check if byte swapping is necessary for the current system using dtype attribute byteorder
 
 
import numpy as np

arr = np.array([1, 256, 65536], dtype=np.int32)
byte_order = arr.dtype.byteorder
print("Byte order of the array:", byte_order)

Byte order of the array: =


In [72]:
 # 76: Create a NumPy array arr1 and a copy of it. Modify an element in the copy and check if it affects arr1
 
 
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
copy_arr = arr1.copy()
copy_arr[0] = 100

print("Original array:", arr1)
print("Copied and modified array:", copy_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Copied and modified array: [100   2   3   4   5   6   7   8   9  10]


In [73]:
# 77: Create a 2D NumPy array matrix, extract a slice, modify it, and observe changes in the original
 
 
import numpy as np

matrix = np.random.randint(1, 101, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 999

print("Original matrix:\n", matrix)
print("View slice after modification:\n", view_slice)

Original matrix:
 [[999  96  44]
 [ 92  31  67]
 [ 32  47  43]]
View slice after modification:
 [[999  96]
 [ 92  31]]


In [74]:
 # 78: Create a NumPy array array_a, extract a slice, broadcast addition, and check if it alters the original
 
 
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]

view_b += 5

print("Original array after broadcasting addition:\n", array_a)

Original array after broadcasting addition:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


In [75]:
 # 79: Create a NumPy array orig_array, reshape it, modify an element in the reshaped view, and check changes
 
 
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 999

print("Original array after modifying reshaped view:\n", orig_array)
print("Reshaped view after modification:\n", reshaped_view)

Original array after modifying reshaped view:
 [[999   2   3   4]
 [  5   6   7   8]]
Reshaped view after modification:
 [[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [76]:
 # 80: Create a NumPy array data, extract a copy of elements greater than 5, modify it, and verify changes
 
 
import numpy as np

data = np.random.randint(1, 11, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 999

print("Original data array:\n", data)
print("Data copy after modification:\n", data_copy)

Original data array:
 [[10  5  9  3]
 [ 6  4  3  4]
 [ 2 10  7  2]]
Data copy after modification:
 [999   9   6  10   7]


In [77]:
# 81: Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them
 
 
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition_result = A + B
subtraction_result = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition of A and B:\n", addition_result)
print("Subtraction of A and B:\n", subtraction_result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [78]:
# 82: Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication
 
 
import numpy as np

C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

matrix_multiplication_result = np.dot(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Matrix multiplication of C and D:\n", matrix_multiplication_result)

Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]
Matrix multiplication of C and D:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [79]:
 # 83: Create a matrix E and find its transpose
 
 
import numpy as np

E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose_E = np.transpose(E)

print("Matrix E:\n", E)
print("Transpose of E:\n", transpose_E)

Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [80]:
# 84: Generate a square matrix F and compute its determinant
 
 
import numpy as np

F = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
determinant_F = np.linalg.det(F)

print("Matrix F:\n", F)
print("Determinant of F:", determinant_F)

Matrix F:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant of F: 0.9999999999999964


In [81]:
 # 85: Create a square matrix G and find its inverse
 
 
import numpy as np

G = np.array([[4, 7], [2, 6]])
inverse_G = np.linalg.inv(G)

print("Matrix G:\n", G)
print("Inverse of G:\n", inverse_G)

Matrix G:
 [[4 7]
 [2 6]]
Inverse of G:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
